In [122]:
import pandas as pd
import numpy as np

In [123]:
df=pd.read_csv('used_cars_dataset.csv')
print(f"Dataset Shape: {df.shape}")
df.head(10)

Dataset Shape: (3000, 18)

,listing_id,brand,model,year,mileage_km,transmission,fuel_type,engine_cc,body_type,color,city,seller_type,accident_history,previous_owners,condition_rating,photos_count,price_egp,sold_within_30_days
0,CAR-52762,MG,ZS,2021,64900.0,Automatic,Diesel,1500.0,SUV,Black,Giza,Individual,No,1.0,Fair,8.0,655000,Yes
1,CAR-52678,Kia,Cerato,2023,NaN,Automatic,Diesel,1600.0,Sedan,Grey,Giza,Individual,No,1.0,Good,12.0,1012000,No
2,CAR-52822,Skoda,Octavia,2009,224500.0,Automatic,Petrol,1400.0,Sedan,Silver,Banha,Dealer,Yes,2.0,Fair,11.0,229000,No
3,CAR-51133,Fiat,Tipo,2019,103800.0,Automatic,Petrol,1600.0,Sedan,Silver,ALEXANDRIA,Individual,No,2.0,Fair,7.0,319000,No
4,CAR-51465,Mitsubishi,Lancer,2022,50200.0,Manual,Hybrid,1600.0,Sedan,White,Cairo,Individual,No,NaN,Fair,8.0,425000,No
5,CAR-52832,Skoda,Octavia,2010,220900.0,Automatic,Diesel,1400.0,Sedan,Black,Giza,Dealer,Yes,1.0,Fair,10.0,191000,Yes
6,CAR-52054,Toyota,Corolla,2023,27100.0,Automatic,Petrol,1600.0,Sedan,Black,Giza,Individual,No,1.0,Good,12.0,1532000,No
7,CAR-51659,Hyundai,Elantra,2022,46900.0,Manual,Petrol,2000.0,Sedan,Blue,Alexandria,Individual,No,2.0,Good,6.0,774000,No
8,CAR-52711,Toyota,Corolla,2022,66100.0,Manual,Petrol,1600.0,Sedan,Black,Giza,Individual,Yes,3.0,Excellent,14.0,1091000,No
9,CAR-51630,MG,ZS,2017,NaN,Automatic,Petrol,1500.0,SUV,White,MANSOURA,Individual,No,3.0,Good,8.0,416000,No

In [124]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   listing_id           3000 non-null   str
 1   brand                3000 non-null   str
 2   model                3000 non-null   str
 3   year                 3000 non-null   int64
 4   mileage_km           2822 non-null   float64
 5   transmission         2941 non-null   str
 6   fuel_type            2940 non-null   str
 7   engine_cc            2879 non-null   float64
 8   body_type            3000 non-null   str
 9   color                2851 non-null   str
 10  city                 2941 non-null   str
 11  seller_type          2942 non-null   str
 12  accident_history     3000 non-null   str
 13  previous_owners      2881 non-null   float64
 14  condition_rating     2851 non-null   str
 15  photos_count         2907 non-null   float64
 16  price_egp            3000 non-null   int64
 17  sold_within_30_days  3000 non-null   str
dtypes: float64(4), int64(2), str(12)
memory usage: 422.0 KB

In [125]:
df.duplicated().sum()

np.int64(40)

In [126]:
df.drop_duplicates(inplace=True)

In [127]:
df.duplicated().sum()

np.int64(0)

In [128]:
df.describe()

,year,mileage_km,engine_cc,previous_owners,photos_count,price_egp
count,2960.000000,2.785000e+03,2840.000000,2843.000000,2871.000000,2.960000e+03
mean,2018.161486,1.094776e+05,1654.720070,1.887091,10.551724,7.559838e+05
std,37.522645,2.724375e+05,529.409892,1.009587,8.435574,2.056189e+06
min,0.000000,0.000000e+00,0.000000,1.000000,0.000000,0.000000e+00
25%,2017.000000,5.040000e+04,1500.000000,1.000000,8.000000,3.290000e+05
50%,2020.000000,8.570000e+04,1600.000000,2.000000,10.000000,5.525000e+05
75%,2022.000000,1.335000e+05,1600.000000,2.000000,13.000000,9.385000e+05
max,2050.000000,9.999999e+06,20000.000000,6.000000,300.000000,1.000000e+08

In [129]:
df.describe(include=object)

C:\Users\hp\AppData\Local\Temp\ipykernel_13332\3998025828.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include=object)

,listing_id,brand,model,transmission,fuel_type,body_type,color,city,seller_type,accident_history,condition_rating,sold_within_30_days
count,2960,2960,2960,2901,2901,2960,2813,2902,2902,2960,2812,2960
unique,2940,53,14,4,3,2,7,27,4,4,4,2
top,CAR-52054,Hyundai,Corolla,Automatic,Petrol,Sedan,White,Cairo,Individual,No,Good,No
freq,2,481,404,1901,1977,2487,783,826,1925,2362,1412,1615

In [130]:
df.isnull().sum()

listing_id               0
brand                    0
model                    0
year                     0
mileage_km             175
transmission            59
fuel_type               59
engine_cc              120
body_type                0
color                  147
city                    58
seller_type             58
accident_history         0
previous_owners        117
condition_rating       148
photos_count            89
price_egp                0
sold_within_30_days      0
dtype: int64

In [131]:
(df.isnull().mean()*100).round(2)

listing_id             0.00
brand                  0.00
model                  0.00
year                   0.00
mileage_km             5.91
transmission           1.99
fuel_type              1.99
engine_cc              4.05
body_type              0.00
color                  4.97
city                   1.96
seller_type            1.96
accident_history       0.00
previous_owners        3.95
condition_rating       5.00
photos_count           3.01
price_egp              0.00
sold_within_30_days    0.00
dtype: float64

In [132]:
df["missing_count"] = df.isnull().sum(axis=1)
df

,listing_id,brand,model,year,mileage_km,transmission,fuel_type,engine_cc,body_type,color,city,seller_type,accident_history,previous_owners,condition_rating,photos_count,price_egp,sold_within_30_days,missing_count
0,CAR-52762,MG,ZS,2021,64900.0,Automatic,Diesel,1500.0,SUV,Black,Giza,Individual,No,1.0,Fair,8.0,655000,Yes,0
1,CAR-52678,Kia,Cerato,2023,NaN,Automatic,Diesel,1600.0,Sedan,Grey,Giza,Individual,No,1.0,Good,12.0,1012000,No,1
2,CAR-52822,Skoda,Octavia,2009,224500.0,Automatic,Petrol,1400.0,Sedan,Silver,Banha,Dealer,Yes,2.0,Fair,11.0,229000,No,0
3,CAR-51133,Fiat,Tipo,2019,103800.0,Automatic,Petrol,1600.0,Sedan,Silver,ALEXANDRIA,Individual,No,2.0,Fair,7.0,319000,No,0
4,CAR-51465,Mitsubishi,Lancer,2022,50200.0,Manual,Hybrid,1600.0,Sedan,White,Cairo,Individual,No,NaN,Fair,8.0,425000,No,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,CAR-51818,Chery,Tiggo 7,2023,40800.0,Manual,Petrol,1600.0,SUV,Grey,Assiut,Individual,No,3.0,Good,7.0,1065000,No,0
2996,CAR-51600,bmw,320i,2022,60400.0,Automatic,Petrol,2000.0,Sedan,Red,Cairo,Individual,No,2.0,NaN,10.0,1409000,Yes,1
2997,CAR-50347,Hyundai,Tucson,2020,87100.0,Auto,Diesel,1600.0,SUV,Blue,Giza,Individual,No,1.0,Good,8.0,966000,Yes,0
2998,CAR-50986,Toyota,Corolla,2020,73900.0,Manual,Diesel,1800.0,Sedan,Silver,Alexandria,Individual,No,4.0,Excellent,12.0,774000,No,0
2999,CAR-50666,Kia,Cerato,2024,14100.0,Automatic,Petrol,1600.0,Sedan,White,Banha,Dealer,No,1.0,Good,14.0,1133000,Yes,0

In [133]:
df=df[df["missing_count"] < 3]

In [134]:
df.drop(columns="missing_count" , inplace=True)

In [135]:
df

,listing_id,brand,model,year,mileage_km,transmission,fuel_type,engine_cc,body_type,color,city,seller_type,accident_history,previous_owners,condition_rating,photos_count,price_egp,sold_within_30_days
0,CAR-52762,MG,ZS,2021,64900.0,Automatic,Diesel,1500.0,SUV,Black,Giza,Individual,No,1.0,Fair,8.0,655000,Yes
1,CAR-52678,Kia,Cerato,2023,NaN,Automatic,Diesel,1600.0,Sedan,Grey,Giza,Individual,No,1.0,Good,12.0,1012000,No
2,CAR-52822,Skoda,Octavia,2009,224500.0,Automatic,Petrol,1400.0,Sedan,Silver,Banha,Dealer,Yes,2.0,Fair,11.0,229000,No
3,CAR-51133,Fiat,Tipo,2019,103800.0,Automatic,Petrol,1600.0,Sedan,Silver,ALEXANDRIA,Individual,No,2.0,Fair,7.0,319000,No
4,CAR-51465,Mitsubishi,Lancer,2022,50200.0,Manual,Hybrid,1600.0,Sedan,White,Cairo,Individual,No,NaN,Fair,8.0,425000,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,CAR-51818,Chery,Tiggo 7,2023,40800.0,Manual,Petrol,1600.0,SUV,Grey,Assiut,Individual,No,3.0,Good,7.0,1065000,No
2996,CAR-51600,bmw,320i,2022,60400.0,Automatic,Petrol,2000.0,Sedan,Red,Cairo,Individual,No,2.0,NaN,10.0,1409000,Yes
2997,CAR-50347,Hyundai,Tucson,2020,87100.0,Auto,Diesel,1600.0,SUV,Blue,Giza,Individual,No,1.0,Good,8.0,966000,Yes
2998,CAR-50986,Toyota,Corolla,2020,73900.0,Manual,Diesel,1800.0,Sedan,Silver,Alexandria,Individual,No,4.0,Excellent,12.0,774000,No
2999,CAR-50666,Kia,Cerato,2024,14100.0,Automatic,Petrol,1600.0,Sedan,White,Banha,Dealer,No,1.0,Good,14.0,1133000,Yes

In [136]:
df["listing_id"].duplicated().sum()

np.int64(20)

In [137]:
df[df["listing_id"].duplicated(keep=False)].sort_values("listing_id")

,listing_id,brand,model,year,mileage_km,transmission,fuel_type,engine_cc,body_type,color,city,seller_type,accident_history,previous_owners,condition_rating,photos_count,price_egp,sold_within_30_days
2159,CAR-50129,Mitsubishi,Lancer,2021,87100.0,Automatic,Petrol,1600.0,Sedan,Black,Giza,Individual,No,2.0,Excellent,7.0,329000,Yes
446,CAR-50129,Mitsubishi,Lancer,2021,87100.0,Automatic,Petrol,1600.0,Sedan,Black,Giza,Individual,No,2.0,Excellent,7.0,339000,Yes
2048,CAR-50342,Mercedes-Benz,C200,2017,130400.0,Automatic,Petrol,1600.0,Sedan,Black,Port Said,Individual,No,1.0,Good,10.0,1213000,No
2868,CAR-50342,Mercedes-Benz,C200,2017,130400.0,Automatic,Petrol,1600.0,Sedan,Black,Port Said,Individual,No,1.0,Good,10.0,1177000,No
1169,CAR-50457,MG,ZS,2024,24800.0,Automatic,Hybrid,1500.0,SUV,Black,Alexandria,Dealer,No,2.0,Fair,12.0,1080000,Yes
2383,CAR-50457,MG,ZS,2024,24800.0,Automatic,Hybrid,1500.0,SUV,Black,Alexandria,Dealer,No,2.0,Fair,12.0,1113000,Yes
2873,CAR-50518,Mercedes-Benz,C200,2020,85300.0,Automatic,Petrol,1600.0,Sedan,Blue,Giza,Dealer,No,1.0,Excellent,14.0,1637000,No
2777,CAR-50518,Mercedes-Benz,C200,2020,85300.0,Automatic,Petrol,1600.0,Sedan,Blue,Giza,Dealer,No,1.0,Excellent,14.0,1688000,No
2432,CAR-50519,Hyundai,Elantra,2019,90900.0,Automatic,Diesel,1600.0,Sedan,Grey,Cairo,Individual,No,5.0,Good,8.0,540000,No
1863,CAR-50519,Hyundai,Elantra,2019,90900.0,Automatic,Diesel,1600.0,Sedan,Grey,Cairo,Individual,No,5.0,Good,8.0,557000,No
916,CAR-50649,Hyundai,Tucson,2024,21300.0,Automatic,Petrol,1600.0,SUV,Silver,Banha,Individual,No,2.0,Fair,8.0,1528000,No
1956,CAR-50649,Hyundai,Tucson,2024,21300.0,Automatic,Petrol,1600.0,SUV,Silver,Banha,Individual,No,2.0,Fair,8.0,1482000,No
1649,CAR-50812,Hyundai,Elantra,2005,302900.0,Automatic,Petrol,NaN,Sedan,Grey,Port Said,Individual,No,4.0,Fair,5.0,167000,No
145,CAR-50812,Hyundai,Elantra,2005,302900.0,Automatic,Petrol,NaN,Sedan,Grey,Port Said,Individual,No,4.0,Fair,5.0,172000,No
1686,CAR-50966,Hyundai,Elantra,2019,117800.0,Automatic,NaN,1600.0,Sedan,Black,Alexandria,Dealer,No,3.0,Good,10.0,425000,Yes
2174,CAR-50966,Hyundai,Elantra,2019,117800.0,Automatic,NaN,1600.0,Sedan,Black,Alexandria,Dealer,No,3.0,Good,10.0,438000,Yes
245,CAR-51110,BMW,320i,2023,41900.0,Automatic,Petrol,1600.0,Sedan,White,Port Said,Dealer,Yes,3.0,Good,14.0,2428000,No
1775,CAR-51110,BMW,320i,2023,41900.0,Automatic,Petrol,1600.0,Sedan,White,Port Said,Dealer,Yes,3.0,Good,14.0,2355000,No
2187,CAR-51131,Chevrolet,Optra,2024,23200.0,Automatic,Petrol,NaN,Sedan,Grey,CAIRO,Individual,No,2.0,NaN,7.0,446000,No
30,CAR-51131,Chevrolet,Optra,2024,23200.0,Automatic,Petrol,NaN,Sedan,Grey,CAIRO,Individual,No,2.0,NaN,7.0,460000,No
653,CAR-51461,Hyundai,Elantra,2022,50500.0,Automatic,Petrol,2000.0,Sedan,Beige,Alexandria,Individual,No,3.0,Good,12.0,909000,Yes
2595,CAR-51461,Hyundai,Elantra,2022,50500.0,Automatic,Petrol,2000.0,Sedan,Beige,Alexandria,Individual,No,3.0,Good,12.0,937000,Yes
2853,CAR-51555,Renault,Logan,2020,93000.0,Auto,Petrol,1600.0,Sedan,Beige,Assiut,Dealer,No,3.0,Good,16.0,358000,Yes
48,CAR-51555,Renault,Logan,2020,93000.0,Auto,Petrol,1600.0,Sedan,Beige,Assiut,Dealer,No,3.0,Good,16.0,369000,Yes
1852,CAR-51918,MG,ZS,2019,125200.0,NaN,Petrol,1500.0,SUV,White,Cairo,Dealer,No,3.0,Excellent,15.0,646000,Yes
389,CAR-51918,MG,ZS,2019,125200.0,NaN,Petrol,1500.0,SUV,White,Cairo,Dealer,No,3.0,Excellent,15.0,627000,Yes
637,CAR-51976,Toyota,Corolla,2023,58000.0,Manual,Hybrid,NaN,Sedan,White,Suez,Individual,Yes,1.0,Fair,NaN,1064000,Yes
2439,CAR-51976,Toyota,Corolla,2023,58000.0,Manual,Hybrid,NaN,Sedan,White,Suez,Individual,Yes,1.0,Fair,NaN,1032000,Yes
6,CAR-52054,Toyota,Corolla,2023,27100.0,Automatic,Petrol,1600.0,Sedan,Black,Giza,Individual,No,1.0,Good,12.0,1532000,No
1718,CAR-52054,Toyota,Corolla,2023,27100.0,Automatic,Petrol,1600.0,Sedan,Black,Giza,Individual,No,1.0,Good,12.0,1486000,No
1043,CAR-52560,Nissan,Sunny,2016,112400.0,Auto,Petrol,1500.0,Sedan,White,Giza,Individual,No,2.0,Good,9.0,253000,Yes
533,CAR-52560,Nissan,Sunny,2016,112400.0,Auto,Petrol,1500.0,Sedan,White,Giza,Individual,No,2.0,Good,9.0,245000,Yes
963,CAR-52577,Hyundai,Tucson,2021,67000.0,Automatic,Petrol,2000.0,SUV,Blue,Giza,Individual,No,4.0,Good,9.0,1392000,No
1535,CAR-52577,Hyundai,Tucson,2021,67000.0,Automatic,Petrol,2000.0,SUV,Blue,Giza,Individual,No,4.0,Good,9.0,1435000,No
760,CAR-52776,Fiat,Tipo,2020,76800.0,Manual,Petrol,1600.0,Sedan,Beige,Alexandria,Individual,Yes,2.0,Excellent,11.0,328000,Yes
182,CAR-52776,Fiat,Tipo,2020,76800.0,Manual,Petrol,1600.0,Sedan,Beige,Alexandria,Individual,Yes,2.0,Excellent,11.0,318000,Yes
2310,CAR-52796,Toyota,Corolla,2020,54900.0,Auto,Petrol,1800.0,Sedan,White,Alexandria,Dealer,No,1.0,Fair,14.0,983000,No
114,CAR-52796,Toyota,Corolla,2020,54900.0,Auto,Petrol,1800.0,Sedan,White,Alexandria,Dealer,No,1.0,Fair,14.0,954000,No
815,CAR-52854,Hyundai,Tucson,2020,96100.0,Automatic,Petrol,1600.0,SUV,Grey,Alexandria,Dealer,No,1.0,Fair,12.0,905000,No
790,CAR-52854,Hyundai,Tucson,2020,96100.0,Automatic,Petrol,1600.0,SUV,Grey,Alexandria,Dealer,No,1.0,Fair,12.0,878000,No

In [138]:
df.drop_duplicates(subset="listing_id", inplace=True)

In [139]:
df["listing_id"].duplicated().sum()

np.int64(0)

In [140]:
df

,listing_id,brand,model,year,mileage_km,transmission,fuel_type,engine_cc,body_type,color,city,seller_type,accident_history,previous_owners,condition_rating,photos_count,price_egp,sold_within_30_days
0,CAR-52762,MG,ZS,2021,64900.0,Automatic,Diesel,1500.0,SUV,Black,Giza,Individual,No,1.0,Fair,8.0,655000,Yes
1,CAR-52678,Kia,Cerato,2023,NaN,Automatic,Diesel,1600.0,Sedan,Grey,Giza,Individual,No,1.0,Good,12.0,1012000,No
2,CAR-52822,Skoda,Octavia,2009,224500.0,Automatic,Petrol,1400.0,Sedan,Silver,Banha,Dealer,Yes,2.0,Fair,11.0,229000,No
3,CAR-51133,Fiat,Tipo,2019,103800.0,Automatic,Petrol,1600.0,Sedan,Silver,ALEXANDRIA,Individual,No,2.0,Fair,7.0,319000,No
4,CAR-51465,Mitsubishi,Lancer,2022,50200.0,Manual,Hybrid,1600.0,Sedan,White,Cairo,Individual,No,NaN,Fair,8.0,425000,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,CAR-51818,Chery,Tiggo 7,2023,40800.0,Manual,Petrol,1600.0,SUV,Grey,Assiut,Individual,No,3.0,Good,7.0,1065000,No
2996,CAR-51600,bmw,320i,2022,60400.0,Automatic,Petrol,2000.0,Sedan,Red,Cairo,Individual,No,2.0,NaN,10.0,1409000,Yes
2997,CAR-50347,Hyundai,Tucson,2020,87100.0,Auto,Diesel,1600.0,SUV,Blue,Giza,Individual,No,1.0,Good,8.0,966000,Yes
2998,CAR-50986,Toyota,Corolla,2020,73900.0,Manual,Diesel,1800.0,Sedan,Silver,Alexandria,Individual,No,4.0,Excellent,12.0,774000,No
2999,CAR-50666,Kia,Cerato,2024,14100.0,Automatic,Petrol,1600.0,Sedan,White,Banha,Dealer,No,1.0,Good,14.0,1133000,Yes

In [141]:
df.isnull().sum()

listing_id               0
brand                    0
model                    0
year                     0
mileage_km             169
transmission            57
fuel_type               57
engine_cc              115
body_type                0
color                  142
city                    58
seller_type             57
accident_history         0
previous_owners        113
condition_rating       145
photos_count            85
price_egp                0
sold_within_30_days      0
dtype: int64

In [142]:
cols = [
    "transmission",
    "fuel_type",
    "color",
    "city",
    "seller_type"
]

df[cols] = df[cols].fillna("Unknown")
df

,listing_id,brand,model,year,mileage_km,transmission,fuel_type,engine_cc,body_type,color,city,seller_type,accident_history,previous_owners,condition_rating,photos_count,price_egp,sold_within_30_days
0,CAR-52762,MG,ZS,2021,64900.0,Automatic,Diesel,1500.0,SUV,Black,Giza,Individual,No,1.0,Fair,8.0,655000,Yes
1,CAR-52678,Kia,Cerato,2023,NaN,Automatic,Diesel,1600.0,Sedan,Grey,Giza,Individual,No,1.0,Good,12.0,1012000,No
2,CAR-52822,Skoda,Octavia,2009,224500.0,Automatic,Petrol,1400.0,Sedan,Silver,Banha,Dealer,Yes,2.0,Fair,11.0,229000,No
3,CAR-51133,Fiat,Tipo,2019,103800.0,Automatic,Petrol,1600.0,Sedan,Silver,ALEXANDRIA,Individual,No,2.0,Fair,7.0,319000,No
4,CAR-51465,Mitsubishi,Lancer,2022,50200.0,Manual,Hybrid,1600.0,Sedan,White,Cairo,Individual,No,NaN,Fair,8.0,425000,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,CAR-51818,Chery,Tiggo 7,2023,40800.0,Manual,Petrol,1600.0,SUV,Grey,Assiut,Individual,No,3.0,Good,7.0,1065000,No
2996,CAR-51600,bmw,320i,2022,60400.0,Automatic,Petrol,2000.0,Sedan,Red,Cairo,Individual,No,2.0,NaN,10.0,1409000,Yes
2997,CAR-50347,Hyundai,Tucson,2020,87100.0,Auto,Diesel,1600.0,SUV,Blue,Giza,Individual,No,1.0,Good,8.0,966000,Yes
2998,CAR-50986,Toyota,Corolla,2020,73900.0,Manual,Diesel,1800.0,Sedan,Silver,Alexandria,Individual,No,4.0,Excellent,12.0,774000,No
2999,CAR-50666,Kia,Cerato,2024,14100.0,Automatic,Petrol,1600.0,Sedan,White,Banha,Dealer,No,1.0,Good,14.0,1133000,Yes

In [143]:
df.isnull().sum()

listing_id               0
brand                    0
model                    0
year                     0
mileage_km             169
transmission             0
fuel_type                0
engine_cc              115
body_type                0
color                    0
city                     0
seller_type              0
accident_history         0
previous_owners        113
condition_rating       145
photos_count            85
price_egp                0
sold_within_30_days      0
dtype: int64

In [144]:

df["condition_rating"].value_counts()

condition_rating
Good         1400
Fair          639
Excellent     568
Poor          180
Name: count, dtype: int64

In [145]:

df['condition_rating_num'] = (
    df['condition_rating']
    .str.strip().str.title()
    .replace({'Poor': 1, 'Fair': 2, 'Good': 3, 'Excellent': 4})
    .astype(float)
)

In [146]:
df

,listing_id,brand,model,year,mileage_km,transmission,fuel_type,engine_cc,body_type,color,city,seller_type,accident_history,previous_owners,condition_rating,photos_count,price_egp,sold_within_30_days,condition_rating_num
0,CAR-52762,MG,ZS,2021,64900.0,Automatic,Diesel,1500.0,SUV,Black,Giza,Individual,No,1.0,Fair,8.0,655000,Yes,2.0
1,CAR-52678,Kia,Cerato,2023,NaN,Automatic,Diesel,1600.0,Sedan,Grey,Giza,Individual,No,1.0,Good,12.0,1012000,No,3.0
2,CAR-52822,Skoda,Octavia,2009,224500.0,Automatic,Petrol,1400.0,Sedan,Silver,Banha,Dealer,Yes,2.0,Fair,11.0,229000,No,2.0
3,CAR-51133,Fiat,Tipo,2019,103800.0,Automatic,Petrol,1600.0,Sedan,Silver,ALEXANDRIA,Individual,No,2.0,Fair,7.0,319000,No,2.0
4,CAR-51465,Mitsubishi,Lancer,2022,50200.0,Manual,Hybrid,1600.0,Sedan,White,Cairo,Individual,No,NaN,Fair,8.0,425000,No,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,CAR-51818,Chery,Tiggo 7,2023,40800.0,Manual,Petrol,1600.0,SUV,Grey,Assiut,Individual,No,3.0,Good,7.0,1065000,No,3.0
2996,CAR-51600,bmw,320i,2022,60400.0,Automatic,Petrol,2000.0,Sedan,Red,Cairo,Individual,No,2.0,NaN,10.0,1409000,Yes,NaN
2997,CAR-50347,Hyundai,Tucson,2020,87100.0,Auto,Diesel,1600.0,SUV,Blue,Giza,Individual,No,1.0,Good,8.0,966000,Yes,3.0
2998,CAR-50986,Toyota,Corolla,2020,73900.0,Manual,Diesel,1800.0,Sedan,Silver,Alexandria,Individual,No,4.0,Excellent,12.0,774000,No,4.0
2999,CAR-50666,Kia,Cerato,2024,14100.0,Automatic,Petrol,1600.0,Sedan,White,Banha,Dealer,No,1.0,Good,14.0,1133000,Yes,3.0

In [147]:
df.isnull().sum()

listing_id                0
brand                     0
model                     0
year                      0
mileage_km              169
transmission              0
fuel_type                 0
engine_cc               115
body_type                 0
color                     0
city                      0
seller_type               0
accident_history          0
previous_owners         113
condition_rating        145
photos_count             85
price_egp                 0
sold_within_30_days       0
condition_rating_num    145
dtype: int64

In [148]:
df["brand"].value_counts()

brand
Hyundai          472
Toyota           372
Nissan           284
Kia              249
Chevrolet        199
MG               188
Renault          179
Skoda            162
Fiat             154
Chery            130
BMW              127
Mercedes-Benz    109
Mitsubishi        97
hyundai           18
toyota            17
chevrolet         12
nissan            11
Hyundai           10
TOYOTA             8
HYUNDAI            8
skoda              8
chery              7
mg                 7
Mercedes           6
KIA                6
kia                6
mitsubishi         6
NISSAN             6
Nissan             6
bmw                6
CHERY              5
fiat               5
mercedes-benz      5
Toyota             4
Chery              4
SKODA              4
renault            4
Chevrolet          4
CHEVROLET          3
RENAULT            3
MERCEDES-BENZ      3
hyundai            2
BMW                2
MITSUBISHI         2
Renault            2
Skoda              2
Fiat               2
Kia                1
MG                 1
NISSAN             1
FIAT               1
Mitsubishi         1
bmw                1
Name: count, dtype: int64

In [149]:
df['brand'] = df['brand'].str.strip().str.title()

df['brand'] = df['brand'].replace({
    'Bmw': 'BMW',
    'Mg': 'MG',
    'Mercedes': 'Mercedes-Benz',
    'Mercedes Benz': 'Mercedes-Benz',
})

In [150]:
df['brand'].value_counts()

brand
Hyundai          510
Toyota           401
Nissan           308
Kia              262
Chevrolet        218
MG               196
Renault          188
Skoda            176
Fiat             162
Chery            146
BMW              136
Mercedes-Benz    123
Mitsubishi       106
Name: count, dtype: int64

In [151]:
df.isnull().sum()

listing_id                0
brand                     0
model                     0
year                      0
mileage_km              169
transmission              0
fuel_type                 0
engine_cc               115
body_type                 0
color                     0
city                      0
seller_type               0
accident_history          0
previous_owners         113
condition_rating        145
photos_count             85
price_egp                 0
sold_within_30_days       0
condition_rating_num    145
dtype: int64

In [152]:
for c in ['model', 'city', 'color', 'fuel_type', 'body_type', 'seller_type', 'transmission']:
    df[c] = df[c].str.strip().str.title()

In [153]:
df['transmission'] = df['transmission'].replace({'Auto': 'Automatic'})
df['body_type'] =df['body_type'].replace({'Suv' : 'SUV'})

In [154]:
df ['model'].value_counts()

model
Corolla    401
Elantra    386
Sunny      308
Cerato     262
Optra      218
Zs         196
Logan      188
Octavia    176
Tipo       162
Tiggo 7    146
320I       136
Tucson     124
C200       123
Lancer     106
Name: count, dtype: int64

In [155]:
df['model'] = df['model'].replace({'320I': '320i'})

In [156]:
df.isnull().sum()

listing_id                0
brand                     0
model                     0
year                      0
mileage_km              169
transmission              0
fuel_type                 0
engine_cc               115
body_type                 0
color                     0
city                      0
seller_type               0
accident_history          0
previous_owners         113
condition_rating        145
photos_count             85
price_egp                 0
sold_within_30_days       0
condition_rating_num    145
dtype: int64

In [157]:
df

,listing_id,brand,model,year,mileage_km,transmission,fuel_type,engine_cc,body_type,color,city,seller_type,accident_history,previous_owners,condition_rating,photos_count,price_egp,sold_within_30_days,condition_rating_num
0,CAR-52762,MG,Zs,2021,64900.0,Automatic,Diesel,1500.0,SUV,Black,Giza,Individual,No,1.0,Fair,8.0,655000,Yes,2.0
1,CAR-52678,Kia,Cerato,2023,NaN,Automatic,Diesel,1600.0,Sedan,Grey,Giza,Individual,No,1.0,Good,12.0,1012000,No,3.0
2,CAR-52822,Skoda,Octavia,2009,224500.0,Automatic,Petrol,1400.0,Sedan,Silver,Banha,Dealer,Yes,2.0,Fair,11.0,229000,No,2.0
3,CAR-51133,Fiat,Tipo,2019,103800.0,Automatic,Petrol,1600.0,Sedan,Silver,Alexandria,Individual,No,2.0,Fair,7.0,319000,No,2.0
4,CAR-51465,Mitsubishi,Lancer,2022,50200.0,Manual,Hybrid,1600.0,Sedan,White,Cairo,Individual,No,NaN,Fair,8.0,425000,No,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,CAR-51818,Chery,Tiggo 7,2023,40800.0,Manual,Petrol,1600.0,SUV,Grey,Assiut,Individual,No,3.0,Good,7.0,1065000,No,3.0
2996,CAR-51600,BMW,320i,2022,60400.0,Automatic,Petrol,2000.0,Sedan,Red,Cairo,Individual,No,2.0,NaN,10.0,1409000,Yes,NaN
2997,CAR-50347,Hyundai,Tucson,2020,87100.0,Automatic,Diesel,1600.0,SUV,Blue,Giza,Individual,No,1.0,Good,8.0,966000,Yes,3.0
2998,CAR-50986,Toyota,Corolla,2020,73900.0,Manual,Diesel,1800.0,Sedan,Silver,Alexandria,Individual,No,4.0,Excellent,12.0,774000,No,4.0
2999,CAR-50666,Kia,Cerato,2024,14100.0,Automatic,Petrol,1600.0,Sedan,White,Banha,Dealer,No,1.0,Good,14.0,1133000,Yes,3.0

In [158]:

df['mileage_km'] = df['mileage_km'].fillna(df.groupby('year')['mileage_km'].transform('median'))
df['engine_cc'] = df['engine_cc'].fillna(df.groupby('model')['engine_cc'].transform('median'))
df['previous_owners'] = df['previous_owners'].fillna(df.groupby('year')['previous_owners'].transform('median')).round()

In [159]:
df.isnull().sum()

listing_id                0
brand                     0
model                     0
year                      0
mileage_km                0
transmission              0
fuel_type                 0
engine_cc                 0
body_type                 0
color                     0
city                      0
seller_type               0
accident_history          0
previous_owners           0
condition_rating        145
photos_count             85
price_egp                 0
sold_within_30_days       0
condition_rating_num    145
dtype: int64

In [160]:
df['photos_count'] = df['photos_count'].fillna(0)

In [161]:

df['condition_rating_num'] = df['condition_rating_num'].fillna(
df.groupby('accident_history')['condition_rating_num'].transform('median')).round()

In [162]:

df['condition_rating'] = df['condition_rating_num'].replace({1: 'Poor', 2: 'Fair', 3: 'Good', 4: 'Excellent'})
df=df.drop(columns=['condition_rating_num'])

In [163]:
df.isnull().sum().sum()

np.int64(0)

In [164]:
df

,listing_id,brand,model,year,mileage_km,transmission,fuel_type,engine_cc,body_type,color,city,seller_type,accident_history,previous_owners,condition_rating,photos_count,price_egp,sold_within_30_days
0,CAR-52762,MG,Zs,2021,64900.0,Automatic,Diesel,1500.0,SUV,Black,Giza,Individual,No,1.0,Fair,8.0,655000,Yes
1,CAR-52678,Kia,Cerato,2023,42100.0,Automatic,Diesel,1600.0,Sedan,Grey,Giza,Individual,No,1.0,Good,12.0,1012000,No
2,CAR-52822,Skoda,Octavia,2009,224500.0,Automatic,Petrol,1400.0,Sedan,Silver,Banha,Dealer,Yes,2.0,Fair,11.0,229000,No
3,CAR-51133,Fiat,Tipo,2019,103800.0,Automatic,Petrol,1600.0,Sedan,Silver,Alexandria,Individual,No,2.0,Fair,7.0,319000,No
4,CAR-51465,Mitsubishi,Lancer,2022,50200.0,Manual,Hybrid,1600.0,Sedan,White,Cairo,Individual,No,2.0,Fair,8.0,425000,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,CAR-51818,Chery,Tiggo 7,2023,40800.0,Manual,Petrol,1600.0,SUV,Grey,Assiut,Individual,No,3.0,Good,7.0,1065000,No
2996,CAR-51600,BMW,320i,2022,60400.0,Automatic,Petrol,2000.0,Sedan,Red,Cairo,Individual,No,2.0,Good,10.0,1409000,Yes
2997,CAR-50347,Hyundai,Tucson,2020,87100.0,Automatic,Diesel,1600.0,SUV,Blue,Giza,Individual,No,1.0,Good,8.0,966000,Yes
2998,CAR-50986,Toyota,Corolla,2020,73900.0,Manual,Diesel,1800.0,Sedan,Silver,Alexandria,Individual,No,4.0,Excellent,12.0,774000,No
2999,CAR-50666,Kia,Cerato,2024,14100.0,Automatic,Petrol,1600.0,Sedan,White,Banha,Dealer,No,1.0,Good,14.0,1133000,Yes

In [165]:
df.info()

<class 'pandas.DataFrame'>
Index: 2932 entries, 0 to 2999
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   listing_id           2932 non-null   str
 1   brand                2932 non-null   str
 2   model                2932 non-null   str
 3   year                 2932 non-null   int64
 4   mileage_km           2932 non-null   float64
 5   transmission         2932 non-null   str
 6   fuel_type            2932 non-null   str
 7   engine_cc            2932 non-null   float64
 8   body_type            2932 non-null   str
 9   color                2932 non-null   str
 10  city                 2932 non-null   str
 11  seller_type          2932 non-null   str
 12  accident_history     2932 non-null   str
 13  previous_owners      2932 non-null   float64
 14  condition_rating     2932 non-null   object
 15  photos_count         2932 non-null   float64
 16  price_egp            2932 non-null   int64
 17  sold_within_30_days  2932 non-null   str
dtypes: float64(4), int64(2), object(1), str(11)
memory usage: 435.2+ KB

## Outliers Detection and Handling

### numeric_cols = [
    "year",
    "mileage_km",
    "engine_cc",
    "previous_owners",
    "photos_count",
    "price_egp"
]

In [166]:
df.loc[
    (df["year"] < 1926) | (df["year"] > 2026),
    ["listing_id", "brand", "model", "year"]
].sort_values("year")

     listing_id      brand    model  year
348   CAR-50240    Hyundai  Elantra     0
427   CAR-50057        BMW     320i  1899
2186  CAR-52626       Fiat     Tipo  1900
179   CAR-52472  Chevrolet    Optra  2031
2435  CAR-50660        Kia   Cerato  2035
927   CAR-52897     Toyota  Corolla  2050

In [167]:
df = df.drop(
    df.loc[
        (df["year"] < 1926) | (df["year"] > 2026)
    ].index
)

In [168]:
df.loc[
    df["photos_count"] < 0,
    ["listing_id", "brand", "model", "photos_count"]
]

Empty DataFrame
Columns: [listing_id, brand, model, photos_count]
Index: []

In [169]:
df.nlargest(
    20, "photos_count"
)[["listing_id", "brand", "model", "photos_count"]]

     listing_id          brand    model  photos_count
1390  CAR-52477        Renault    Logan         300.0
2392  CAR-51897        Hyundai   Tucson         250.0
1564  CAR-50415         Toyota  Corolla         150.0
992   CAR-51784        Renault    Logan          99.0
796   CAR-52128            Kia   Cerato          23.0
68    CAR-50378         Toyota  Corolla          21.0
267   CAR-51253      Chevrolet    Optra          21.0
542   CAR-52772         Nissan    Sunny          21.0
651   CAR-52453        Hyundai   Tucson          21.0
792   CAR-51874      Chevrolet    Optra          21.0
1060  CAR-51464            Kia   Cerato          21.0
1339  CAR-51484            Kia   Cerato          21.0
1962  CAR-52569          Chery  Tiggo 7          21.0
2012  CAR-52922         Nissan    Sunny          21.0
150   CAR-50230         Toyota  Corolla          20.0
172   CAR-50634         Nissan    Sunny          20.0
214   CAR-51318      Chevrolet    Optra          20.0
326   CAR-51996        Hyundai  Elantra          20.0
577   CAR-52277  Mercedes-Benz     C200          20.0
780   CAR-50899      Chevrolet    Optra          20.0

In [170]:
df.loc[
    df["previous_owners"] <= 0,
    ["listing_id", "brand", "model", "year", "previous_owners"]
]

Empty DataFrame
Columns: [listing_id, brand, model, year, previous_owners]
Index: []

In [171]:
df.nlargest(
    20, "previous_owners"
)[["listing_id", "brand", "model", "year", "previous_owners"]]

     listing_id          brand    model  year  previous_owners
46    CAR-51436            Kia   Cerato  2008              6.0
716   CAR-52077        Hyundai  Elantra  2007              6.0
751   CAR-51774        Hyundai   Tucson  2016              6.0
808   CAR-51276        Renault    Logan  2020              6.0
974   CAR-50917         Toyota  Corolla  2021              6.0
1369  CAR-50131          Skoda  Octavia  2009              6.0
1473  CAR-50610  Mercedes-Benz     C200  2005              6.0
1479  CAR-50964            BMW     320i  2010              6.0
1574  CAR-50087        Hyundai   Tucson  2014              6.0
1916  CAR-50439           Fiat     Tipo  2005              6.0
1938  CAR-51995            Kia   Cerato  2020              6.0
2230  CAR-52104      Chevrolet    Optra  2019              6.0
2283  CAR-52210        Hyundai  Elantra  2021              6.0
2291  CAR-52150            Kia   Cerato  2005              6.0
2452  CAR-51664         Toyota  Corolla  2014              6.0
2839  CAR-51651             MG       Zs  2016              6.0
2971  CAR-51387      Chevrolet    Optra  2015              6.0
44    CAR-52778        Hyundai  Elantra  2011              5.0
109   CAR-50859         Nissan    Sunny  2012              5.0
112   CAR-51716         Nissan    Sunny  2018              5.0

In [172]:
cols = ["mileage_km", "price_egp", "engine_cc"]

for col in cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)

    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    print(f"\n{'-'*40}")
    print(f"Feature: {col}")
    print(f"Q1: {Q1}")
    print(f"Q3: {Q3}")
    print(f"IQR: {IQR}")
    print(f"Lower Bound: {lower_bound:.2f}")
    print(f"Upper Bound: {upper_bound:.2f}")
    print(f"Actual Min: {df[col].min()}")
    print(f"Actual Max: {df[col].max()}")

    print(
        "Outliers Count:",
        ((df[col] < lower_bound) | (df[col] > upper_bound)).sum()
    )

----------------------------------------
Feature: mileage_km
Q1: 50600.0
Q3: 133650.0
IQR: 83050.0
Lower Bound: -73975.00
Upper Bound: 258225.00
Actual Min: 0.0
Actual Max: 9999999.0
Outliers Count: 89

----------------------------------------
Feature: price_egp
Q1: 329000.0
Q3: 937000.0
IQR: 608000.0
Lower Bound: -583000.00
Upper Bound: 1849000.00
Actual Min: 0
Actual Max: 99999999
Outliers Count: 118

----------------------------------------
Feature: engine_cc
Q1: 1500.0
Q3: 1600.0
IQR: 100.0
Lower Bound: 1350.00
Upper Bound: 1750.00
Actual Min: 0.0
Actual Max: 20000.0
Outliers Count: 714

In [173]:
df.nlargest(20, "mileage_km")[
    ["listing_id", "brand", "model", "year", "mileage_km"]
]

     listing_id          brand    model  year  mileage_km
1816  CAR-50796            Kia   Cerato  2020   9999999.0
2031  CAR-51195        Hyundai  Elantra  2017   8888888.0
2916  CAR-50758  Mercedes-Benz     C200  2024   3000000.0
1874  CAR-50529             MG       Zs  2024   2500000.0
754   CAR-51981         Toyota  Corolla  2022   1500000.0
2787  CAR-50688            BMW     320i  2022   1200000.0
2987  CAR-52257      Chevrolet    Optra  2020   1100000.0
1361  CAR-50581           Fiat     Tipo  2014    999999.0
805   CAR-50112        Renault    Logan  2020    950000.0
2016  CAR-51645        Hyundai  Elantra  2005    374600.0
2354  CAR-51510          Chery  Tiggo 7  2005    368300.0
190   CAR-51310         Toyota  Corolla  2005    352300.0
1371  CAR-50474            Kia   Cerato  2005    349300.0
1426  CAR-50841  Mercedes-Benz     C200  2005    343100.0
1694  CAR-51409            BMW     320i  2005    341300.0
217   CAR-51066          Skoda  Octavia  2005    336200.0
1305  CAR-50244        Hyundai   Tucson  2005    329500.0
1473  CAR-50610  Mercedes-Benz     C200  2005    329100.0
221   CAR-50547             MG       Zs  2005    325600.0
1814  CAR-51556             MG       Zs  2005    322300.0

In [174]:
df = df.drop(
    df.loc[
        df["mileage_km"] > 1_000_000
    ].index
)

In [175]:
df.nsmallest(20, "price_egp")[
    ["listing_id", "brand", "model", "year", "price_egp"]
]

     listing_id       brand    model  year  price_egp
1853  CAR-52208   Chevrolet    Optra  2020          0
2852  CAR-51467     Hyundai  Elantra  2020          0
1004  CAR-52363     Renault    Logan  2012          1
2075  CAR-50081     Hyundai  Elantra  2019          5
594   CAR-50897         Kia   Cerato  2020        150
506   CAR-50219   Chevrolet    Optra  2005      63000
1509  CAR-50008   Chevrolet    Optra  2007      63000
2654  CAR-51447   Chevrolet    Optra  2005      64000
1270  CAR-52272   Chevrolet    Optra  2012      65000
2717  CAR-51408   Chevrolet    Optra  2009      66000
90    CAR-50877   Chevrolet    Optra  2005      72000
2948  CAR-50025   Chevrolet    Optra  2005      72000
165   CAR-52101   Chevrolet    Optra  2013      73000
2791  CAR-50482   Chevrolet    Optra  2010      74000
319   CAR-51904   Chevrolet    Optra  2008      75000
1747  CAR-52548   Chevrolet    Optra  2009      75000
2875  CAR-52076   Chevrolet    Optra  2006      76000
1862  CAR-51472  Mitsubishi   Lancer  2010      77000
1996  CAR-51020  Mitsubishi   Lancer  2009      77000
554   CAR-50091   Chevrolet    Optra  2011      78000

In [176]:
df.nlargest(20, "price_egp")[
    ["listing_id", "brand", "model", "year", "price_egp"]
]

     listing_id          brand    model  year  price_egp
178   CAR-50807         Nissan    Sunny  2008   99999999
2552  CAR-52594          Chery  Tiggo 7  2019   30000000
1182  CAR-51174          Skoda  Octavia  2013   25000000
358   CAR-51635          Skoda  Octavia  2015   18000000
499   CAR-52200        Hyundai  Elantra  2022   12000000
1482  CAR-50772  Mercedes-Benz     C200  2026    3818000
1653  CAR-50036  Mercedes-Benz     C200  2023    3585000
1867  CAR-51610  Mercedes-Benz     C200  2025    3455000
2023  CAR-50448  Mercedes-Benz     C200  2024    3366000
1620  CAR-51265  Mercedes-Benz     C200  2025    3332000
2098  CAR-52614  Mercedes-Benz     C200  2025    3173000
1104  CAR-52332  Mercedes-Benz     C200  2025    3166000
246   CAR-51557            BMW     320i  2024    3144000
2240  CAR-51187            BMW     320i  2025    3001000
1335  CAR-52173  Mercedes-Benz     C200  2024    2937000
765   CAR-50407            BMW     320i  2024    2924000
2111  CAR-52095  Mercedes-Benz     C200  2025    2921000
2499  CAR-52565  Mercedes-Benz     C200  2024    2891000
1666  CAR-52019  Mercedes-Benz     C200  2023    2875000
1359  CAR-50477  Mercedes-Benz     C200  2024    2872000

In [177]:
df = df.drop(
    df.loc[
        (df["price_egp"] < 60_000) |
        (df["price_egp"] > 5_000_000)
    ].index
)

In [178]:
df.nsmallest(20, "engine_cc")[
    ["listing_id", "brand", "model", "year", "engine_cc"]
]

     listing_id      brand    model  year  engine_cc
787   CAR-51241     Nissan    Sunny  2007        0.0
1799  CAR-50572  Chevrolet    Optra  2018        0.0
848   CAR-51964    Hyundai  Elantra  2022        5.0
151   CAR-50191      Skoda  Octavia  2023      100.0
2     CAR-52822      Skoda  Octavia  2009     1400.0
5     CAR-52832      Skoda  Octavia  2010     1400.0
24    CAR-51217      Skoda  Octavia  2019     1400.0
37    CAR-51201       Fiat     Tipo  2012     1400.0
42    CAR-52056       Fiat     Tipo  2023     1400.0
51    CAR-50024       Fiat     Tipo  2023     1400.0
84    CAR-51570       Fiat     Tipo  2024     1400.0
86    CAR-50815      Skoda  Octavia  2016     1400.0
128   CAR-50862       Fiat     Tipo  2020     1400.0
130   CAR-50075      Skoda  Octavia  2016     1400.0
133   CAR-50749      Skoda  Octavia  2015     1400.0
160   CAR-52830       Fiat     Tipo  2018     1400.0
177   CAR-50765       Fiat     Tipo  2022     1400.0
196   CAR-51720      Skoda  Octavia  2014     1400.0
217   CAR-51066      Skoda  Octavia  2005     1400.0
233   CAR-50629       Fiat     Tipo  2018     1400.0

In [179]:
df.nlargest(20, "engine_cc")[
    ["listing_id", "brand", "model", "year", "engine_cc"]
]

     listing_id          brand    model  year  engine_cc
2053  CAR-50949            Kia   Cerato  2017    20000.0
889   CAR-50251          Skoda  Octavia  2021    16000.0
105   CAR-52466      Chevrolet    Optra  2014    12000.0
2374  CAR-52435           Fiat     Tipo  2012     9000.0
7     CAR-51659        Hyundai  Elantra  2022     2000.0
15    CAR-50927        Hyundai   Tucson  2022     2000.0
17    CAR-50370  Mercedes-Benz     C200  2024     2000.0
23    CAR-52348        Hyundai  Elantra  2005     2000.0
26    CAR-50103            BMW     320i  2023     2000.0
39    CAR-51114        Hyundai  Elantra  2022     2000.0
41    CAR-51983        Hyundai  Elantra  2019     2000.0
58    CAR-52244  Mercedes-Benz     C200  2018     2000.0
73    CAR-50982        Hyundai  Elantra  2020     2000.0
98    CAR-51926        Hyundai  Elantra  2019     2000.0
102   CAR-52289            BMW     320i  2015     2000.0
106   CAR-50076            BMW     320i  2024     2000.0
115   CAR-51587        Hyundai  Elantra  2015     2000.0
118   CAR-50206        Hyundai  Elantra  2022     2000.0
120   CAR-51646        Hyundai  Elantra  2023     2000.0
127   CAR-50220        Hyundai  Elantra  2019     2000.0

In [180]:
df = df.drop(
    df.loc[
        (df["engine_cc"] < 1400) | (df["engine_cc"] > 2000)
    ].index
)

In [181]:
df.describe()

,year,mileage_km,engine_cc,previous_owners,photos_count,price_egp
count,2901.000000,2901.000000,2901.000000,2901.000000,2901.000000,2.901000e+03
mean,2018.900379,99558.445019,1639.917270,1.878663,10.250603,6.933151e+05
std,4.577012,68879.221010,170.412866,0.994691,8.564498,5.118877e+05
min,1970.000000,0.000000,1400.000000,1.000000,0.000000,6.300000e+04
25%,2017.000000,50400.000000,1500.000000,1.000000,8.000000,3.310000e+05
50%,2020.000000,85300.000000,1600.000000,2.000000,10.000000,5.520000e+05
75%,2022.000000,133100.000000,1600.000000,2.000000,13.000000,9.320000e+05
max,2026.000000,999999.000000,2000.000000,6.000000,300.000000,3.818000e+06

In [184]:
df.describe(include=object)

C:\Users\hp\AppData\Local\Temp\ipykernel_13332\3998025828.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include=object)

,listing_id,brand,model,transmission,fuel_type,body_type,color,city,seller_type,accident_history,condition_rating,sold_within_30_days
count,2901,2901,2901,2901,2901,2901,2901,2901,2901,2901,2901,2901
unique,2901,13,14,4,4,2,8,10,3,4,4,2
top,CAR-52762,Hyundai,Corolla,Automatic,Petrol,Sedan,White,Cairo,Individual,No,Good,No
freq,1,504,399,2036,1931,2437,769,871,1968,2311,1525,1582

In [183]:
df.to_csv('cleaned_used_cars_dataset.csv', index=False)

# Done.....