In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('used_cars_dataset.csv')
df.head(20)

,listing_id,brand,model,year,mileage_km,transmission,fuel_type,engine_cc,body_type,color,city,seller_type,accident_history,previous_owners,condition_rating,photos_count,price_egp,sold_within_30_days
0,CAR-52762,MG,ZS,2021,64900.0,Automatic,Diesel,1500.0,SUV,Black,Giza,Individual,No,1.0,Fair,8.0,655000,Yes
1,CAR-52678,Kia,Cerato,2023,NaN,Automatic,Diesel,1600.0,Sedan,Grey,Giza,Individual,No,1.0,Good,12.0,1012000,No
2,CAR-52822,Skoda,Octavia,2009,224500.0,Automatic,Petrol,1400.0,Sedan,Silver,Banha,Dealer,Yes,2.0,Fair,11.0,229000,No
3,CAR-51133,Fiat,Tipo,2019,103800.0,Automatic,Petrol,1600.0,Sedan,Silver,ALEXANDRIA,Individual,No,2.0,Fair,7.0,319000,No
4,CAR-51465,Mitsubishi,Lancer,2022,50200.0,Manual,Hybrid,1600.0,Sedan,White,Cairo,Individual,No,NaN,Fair,8.0,425000,No
5,CAR-52832,Skoda,Octavia,2010,220900.0,Automatic,Diesel,1400.0,Sedan,Black,Giza,Dealer,Yes,1.0,Fair,10.0,191000,Yes
6,CAR-52054,Toyota,Corolla,2023,27100.0,Automatic,Petrol,1600.0,Sedan,Black,Giza,Individual,No,1.0,Good,12.0,1532000,No
7,CAR-51659,Hyundai,Elantra,2022,46900.0,Manual,Petrol,2000.0,Sedan,Blue,Alexandria,Individual,No,2.0,Good,6.0,774000,No
8,CAR-52711,Toyota,Corolla,2022,66100.0,Manual,Petrol,1600.0,Sedan,Black,Giza,Individual,Yes,3.0,Excellent,14.0,1091000,No
9,CAR-51630,MG,ZS,2017,NaN,Automatic,Petrol,1500.0,SUV,White,MANSOURA,Individual,No,3.0,Good,8.0,416000,No
10,CAR-50687,Nissan,Sunny,2023,57400.0,Manual,Petrol,1500.0,Sedan,White,Mansoura,Individual,No,3.0,Good,13.0,636000,No
11,CAR-51697,Skoda,Octavia,2023,31800.0,Automatic,Petrol,1800.0,Sedan,Blue,Cairo,Individual,No,1.0,Poor,8.0,1029000,No
12,CAR-52042,Kia,Cerato,2020,88700.0,Automatic,Petrol,1600.0,Sedan,White,Cairo,Individual,Yes,1.0,Good,6.0,490000,Yes
13,CAR-52075,Hyundai,Elantra,2023,48800.0,Auto,Diesel,1600.0,Sedan,White,Cairo,Individual,No,2.0,Good,12.0,1205000,Yes
14,CAR-52497,Kia,Cerato,2025,8500.0,Automatic,Hybrid,1600.0,Sedan,Silver,NaN,Individual,Yes,1.0,Good,6.0,1011000,Yes
15,CAR-50927,Hyundai,Tucson,2022,27000.0,Automatic,Hybrid,2000.0,SUV,NaN,Cairo,Individual,No,2.0,Fair,10.0,1565000,No
16,CAR-50939,Chevrolet,Optra,2022,56700.0,Automatic,Hybrid,NaN,Sedan,NaN,Cairo,Individual,No,3.0,Good,8.0,383000,Yes
17,CAR-50370,Mercedes,C200,2024,13300.0,Automatic,Petrol,2000.0,Sedan,Blue,Assiut,Dealer,Yes,1.0,Fair,8.0,2543000,Yes
18,CAR-51803,MG,ZS,2021,60100.0,Automatic,Petrol,1500.0,SUV,Grey,Assiut,Dealer,No,1.0,Good,8.0,864000,No
19,CAR-52360,TOYOTA,Corolla,2019,101700.0,Automatic,Petrol,1800.0,Sedan,Grey,Suez,Individual,Yes,2.0,Good,8.0,723000,No

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   listing_id           3000 non-null   str
 1   brand                3000 non-null   str
 2   model                3000 non-null   str
 3   year                 3000 non-null   int64
 4   mileage_km           2822 non-null   float64
 5   transmission         2941 non-null   str
 6   fuel_type            2940 non-null   str
 7   engine_cc            2879 non-null   float64
 8   body_type            3000 non-null   str
 9   color                2851 non-null   str
 10  city                 2941 non-null   str
 11  seller_type          2942 non-null   str
 12  accident_history     3000 non-null   str
 13  previous_owners      2881 non-null   float64
 14  condition_rating     2851 non-null   str
 15  photos_count         2907 non-null   float64
 16  price_egp            3000 non-null   int64
 17  sold_within_30_days  3000 non-null   str
dtypes: float64(4), int64(2), str(12)
memory usage: 422.0 KB

In [4]:
df.shape

(3000, 18)

In [5]:
df.duplicated().sum()

np.int64(40)

In [6]:
df.drop_duplicates(inplace=True)

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df.isnull().sum()

listing_id               0
brand                    0
model                    0
year                     0
mileage_km             175
transmission            59
fuel_type               59
engine_cc              120
body_type                0
color                  147
city                    58
seller_type             58
accident_history         0
previous_owners        117
condition_rating       148
photos_count            89
price_egp                0
sold_within_30_days      0
dtype: int64

In [9]:
(df.isnull().mean()*100).round(2)

listing_id             0.00
brand                  0.00
model                  0.00
year                   0.00
mileage_km             5.91
transmission           1.99
fuel_type              1.99
engine_cc              4.05
body_type              0.00
color                  4.97
city                   1.96
seller_type            1.96
accident_history       0.00
previous_owners        3.95
condition_rating       5.00
photos_count           3.01
price_egp              0.00
sold_within_30_days    0.00
dtype: float64

In [10]:
df["missing_count"] = df.isnull().sum(axis=1)
df

,listing_id,brand,model,year,mileage_km,transmission,fuel_type,engine_cc,body_type,color,city,seller_type,accident_history,previous_owners,condition_rating,photos_count,price_egp,sold_within_30_days,missing_count
0,CAR-52762,MG,ZS,2021,64900.0,Automatic,Diesel,1500.0,SUV,Black,Giza,Individual,No,1.0,Fair,8.0,655000,Yes,0
1,CAR-52678,Kia,Cerato,2023,NaN,Automatic,Diesel,1600.0,Sedan,Grey,Giza,Individual,No,1.0,Good,12.0,1012000,No,1
2,CAR-52822,Skoda,Octavia,2009,224500.0,Automatic,Petrol,1400.0,Sedan,Silver,Banha,Dealer,Yes,2.0,Fair,11.0,229000,No,0
3,CAR-51133,Fiat,Tipo,2019,103800.0,Automatic,Petrol,1600.0,Sedan,Silver,ALEXANDRIA,Individual,No,2.0,Fair,7.0,319000,No,0
4,CAR-51465,Mitsubishi,Lancer,2022,50200.0,Manual,Hybrid,1600.0,Sedan,White,Cairo,Individual,No,NaN,Fair,8.0,425000,No,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,CAR-51818,Chery,Tiggo 7,2023,40800.0,Manual,Petrol,1600.0,SUV,Grey,Assiut,Individual,No,3.0,Good,7.0,1065000,No,0
2996,CAR-51600,bmw,320i,2022,60400.0,Automatic,Petrol,2000.0,Sedan,Red,Cairo,Individual,No,2.0,NaN,10.0,1409000,Yes,1
2997,CAR-50347,Hyundai,Tucson,2020,87100.0,Auto,Diesel,1600.0,SUV,Blue,Giza,Individual,No,1.0,Good,8.0,966000,Yes,0
2998,CAR-50986,Toyota,Corolla,2020,73900.0,Manual,Diesel,1800.0,Sedan,Silver,Alexandria,Individual,No,4.0,Excellent,12.0,774000,No,0
2999,CAR-50666,Kia,Cerato,2024,14100.0,Automatic,Petrol,1600.0,Sedan,White,Banha,Dealer,No,1.0,Good,14.0,1133000,Yes,0

In [11]:
df=df[df["missing_count"] < 3]

In [12]:
df.drop(columns="missing_count" , inplace=True)

In [13]:
df

,listing_id,brand,model,year,mileage_km,transmission,fuel_type,engine_cc,body_type,color,city,seller_type,accident_history,previous_owners,condition_rating,photos_count,price_egp,sold_within_30_days
0,CAR-52762,MG,ZS,2021,64900.0,Automatic,Diesel,1500.0,SUV,Black,Giza,Individual,No,1.0,Fair,8.0,655000,Yes
1,CAR-52678,Kia,Cerato,2023,NaN,Automatic,Diesel,1600.0,Sedan,Grey,Giza,Individual,No,1.0,Good,12.0,1012000,No
2,CAR-52822,Skoda,Octavia,2009,224500.0,Automatic,Petrol,1400.0,Sedan,Silver,Banha,Dealer,Yes,2.0,Fair,11.0,229000,No
3,CAR-51133,Fiat,Tipo,2019,103800.0,Automatic,Petrol,1600.0,Sedan,Silver,ALEXANDRIA,Individual,No,2.0,Fair,7.0,319000,No
4,CAR-51465,Mitsubishi,Lancer,2022,50200.0,Manual,Hybrid,1600.0,Sedan,White,Cairo,Individual,No,NaN,Fair,8.0,425000,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,CAR-51818,Chery,Tiggo 7,2023,40800.0,Manual,Petrol,1600.0,SUV,Grey,Assiut,Individual,No,3.0,Good,7.0,1065000,No
2996,CAR-51600,bmw,320i,2022,60400.0,Automatic,Petrol,2000.0,Sedan,Red,Cairo,Individual,No,2.0,NaN,10.0,1409000,Yes
2997,CAR-50347,Hyundai,Tucson,2020,87100.0,Auto,Diesel,1600.0,SUV,Blue,Giza,Individual,No,1.0,Good,8.0,966000,Yes
2998,CAR-50986,Toyota,Corolla,2020,73900.0,Manual,Diesel,1800.0,Sedan,Silver,Alexandria,Individual,No,4.0,Excellent,12.0,774000,No
2999,CAR-50666,Kia,Cerato,2024,14100.0,Automatic,Petrol,1600.0,Sedan,White,Banha,Dealer,No,1.0,Good,14.0,1133000,Yes

In [14]:
df["listing_id"].duplicated().sum()

np.int64(20)

In [15]:
df[df["listing_id"].duplicated(keep=False)].sort_values("listing_id")

,listing_id,brand,model,year,mileage_km,transmission,fuel_type,engine_cc,body_type,color,city,seller_type,accident_history,previous_owners,condition_rating,photos_count,price_egp,sold_within_30_days
2159,CAR-50129,Mitsubishi,Lancer,2021,87100.0,Automatic,Petrol,1600.0,Sedan,Black,Giza,Individual,No,2.0,Excellent,7.0,329000,Yes
446,CAR-50129,Mitsubishi,Lancer,2021,87100.0,Automatic,Petrol,1600.0,Sedan,Black,Giza,Individual,No,2.0,Excellent,7.0,339000,Yes
2048,CAR-50342,Mercedes-Benz,C200,2017,130400.0,Automatic,Petrol,1600.0,Sedan,Black,Port Said,Individual,No,1.0,Good,10.0,1213000,No
2868,CAR-50342,Mercedes-Benz,C200,2017,130400.0,Automatic,Petrol,1600.0,Sedan,Black,Port Said,Individual,No,1.0,Good,10.0,1177000,No
1169,CAR-50457,MG,ZS,2024,24800.0,Automatic,Hybrid,1500.0,SUV,Black,Alexandria,Dealer,No,2.0,Fair,12.0,1080000,Yes
2383,CAR-50457,MG,ZS,2024,24800.0,Automatic,Hybrid,1500.0,SUV,Black,Alexandria,Dealer,No,2.0,Fair,12.0,1113000,Yes
2873,CAR-50518,Mercedes-Benz,C200,2020,85300.0,Automatic,Petrol,1600.0,Sedan,Blue,Giza,Dealer,No,1.0,Excellent,14.0,1637000,No
2777,CAR-50518,Mercedes-Benz,C200,2020,85300.0,Automatic,Petrol,1600.0,Sedan,Blue,Giza,Dealer,No,1.0,Excellent,14.0,1688000,No
2432,CAR-50519,Hyundai,Elantra,2019,90900.0,Automatic,Diesel,1600.0,Sedan,Grey,Cairo,Individual,No,5.0,Good,8.0,540000,No
1863,CAR-50519,Hyundai,Elantra,2019,90900.0,Automatic,Diesel,1600.0,Sedan,Grey,Cairo,Individual,No,5.0,Good,8.0,557000,No
916,CAR-50649,Hyundai,Tucson,2024,21300.0,Automatic,Petrol,1600.0,SUV,Silver,Banha,Individual,No,2.0,Fair,8.0,1528000,No
1956,CAR-50649,Hyundai,Tucson,2024,21300.0,Automatic,Petrol,1600.0,SUV,Silver,Banha,Individual,No,2.0,Fair,8.0,1482000,No
1649,CAR-50812,Hyundai,Elantra,2005,302900.0,Automatic,Petrol,NaN,Sedan,Grey,Port Said,Individual,No,4.0,Fair,5.0,167000,No
145,CAR-50812,Hyundai,Elantra,2005,302900.0,Automatic,Petrol,NaN,Sedan,Grey,Port Said,Individual,No,4.0,Fair,5.0,172000,No
1686,CAR-50966,Hyundai,Elantra,2019,117800.0,Automatic,NaN,1600.0,Sedan,Black,Alexandria,Dealer,No,3.0,Good,10.0,425000,Yes
2174,CAR-50966,Hyundai,Elantra,2019,117800.0,Automatic,NaN,1600.0,Sedan,Black,Alexandria,Dealer,No,3.0,Good,10.0,438000,Yes
245,CAR-51110,BMW,320i,2023,41900.0,Automatic,Petrol,1600.0,Sedan,White,Port Said,Dealer,Yes,3.0,Good,14.0,2428000,No
1775,CAR-51110,BMW,320i,2023,41900.0,Automatic,Petrol,1600.0,Sedan,White,Port Said,Dealer,Yes,3.0,Good,14.0,2355000,No
2187,CAR-51131,Chevrolet,Optra,2024,23200.0,Automatic,Petrol,NaN,Sedan,Grey,CAIRO,Individual,No,2.0,NaN,7.0,446000,No
30,CAR-51131,Chevrolet,Optra,2024,23200.0,Automatic,Petrol,NaN,Sedan,Grey,CAIRO,Individual,No,2.0,NaN,7.0,460000,No
653,CAR-51461,Hyundai,Elantra,2022,50500.0,Automatic,Petrol,2000.0,Sedan,Beige,Alexandria,Individual,No,3.0,Good,12.0,909000,Yes
2595,CAR-51461,Hyundai,Elantra,2022,50500.0,Automatic,Petrol,2000.0,Sedan,Beige,Alexandria,Individual,No,3.0,Good,12.0,937000,Yes
2853,CAR-51555,Renault,Logan,2020,93000.0,Auto,Petrol,1600.0,Sedan,Beige,Assiut,Dealer,No,3.0,Good,16.0,358000,Yes
48,CAR-51555,Renault,Logan,2020,93000.0,Auto,Petrol,1600.0,Sedan,Beige,Assiut,Dealer,No,3.0,Good,16.0,369000,Yes
1852,CAR-51918,MG,ZS,2019,125200.0,NaN,Petrol,1500.0,SUV,White,Cairo,Dealer,No,3.0,Excellent,15.0,646000,Yes
389,CAR-51918,MG,ZS,2019,125200.0,NaN,Petrol,1500.0,SUV,White,Cairo,Dealer,No,3.0,Excellent,15.0,627000,Yes
637,CAR-51976,Toyota,Corolla,2023,58000.0,Manual,Hybrid,NaN,Sedan,White,Suez,Individual,Yes,1.0,Fair,NaN,1064000,Yes
2439,CAR-51976,Toyota,Corolla,2023,58000.0,Manual,Hybrid,NaN,Sedan,White,Suez,Individual,Yes,1.0,Fair,NaN,1032000,Yes
6,CAR-52054,Toyota,Corolla,2023,27100.0,Automatic,Petrol,1600.0,Sedan,Black,Giza,Individual,No,1.0,Good,12.0,1532000,No
1718,CAR-52054,Toyota,Corolla,2023,27100.0,Automatic,Petrol,1600.0,Sedan,Black,Giza,Individual,No,1.0,Good,12.0,1486000,No
1043,CAR-52560,Nissan,Sunny,2016,112400.0,Auto,Petrol,1500.0,Sedan,White,Giza,Individual,No,2.0,Good,9.0,253000,Yes
533,CAR-52560,Nissan,Sunny,2016,112400.0,Auto,Petrol,1500.0,Sedan,White,Giza,Individual,No,2.0,Good,9.0,245000,Yes
963,CAR-52577,Hyundai,Tucson,2021,67000.0,Automatic,Petrol,2000.0,SUV,Blue,Giza,Individual,No,4.0,Good,9.0,1392000,No
1535,CAR-52577,Hyundai,Tucson,2021,67000.0,Automatic,Petrol,2000.0,SUV,Blue,Giza,Individual,No,4.0,Good,9.0,1435000,No
760,CAR-52776,Fiat,Tipo,2020,76800.0,Manual,Petrol,1600.0,Sedan,Beige,Alexandria,Individual,Yes,2.0,Excellent,11.0,328000,Yes
182,CAR-52776,Fiat,Tipo,2020,76800.0,Manual,Petrol,1600.0,Sedan,Beige,Alexandria,Individual,Yes,2.0,Excellent,11.0,318000,Yes
2310,CAR-52796,Toyota,Corolla,2020,54900.0,Auto,Petrol,1800.0,Sedan,White,Alexandria,Dealer,No,1.0,Fair,14.0,983000,No
114,CAR-52796,Toyota,Corolla,2020,54900.0,Auto,Petrol,1800.0,Sedan,White,Alexandria,Dealer,No,1.0,Fair,14.0,954000,No
815,CAR-52854,Hyundai,Tucson,2020,96100.0,Automatic,Petrol,1600.0,SUV,Grey,Alexandria,Dealer,No,1.0,Fair,12.0,905000,No
790,CAR-52854,Hyundai,Tucson,2020,96100.0,Automatic,Petrol,1600.0,SUV,Grey,Alexandria,Dealer,No,1.0,Fair,12.0,878000,No

In [16]:
df.drop_duplicates(subset="listing_id", inplace=True)

In [17]:
df["listing_id"].duplicated().sum()

np.int64(0)

In [18]:
df

,listing_id,brand,model,year,mileage_km,transmission,fuel_type,engine_cc,body_type,color,city,seller_type,accident_history,previous_owners,condition_rating,photos_count,price_egp,sold_within_30_days
0,CAR-52762,MG,ZS,2021,64900.0,Automatic,Diesel,1500.0,SUV,Black,Giza,Individual,No,1.0,Fair,8.0,655000,Yes
1,CAR-52678,Kia,Cerato,2023,NaN,Automatic,Diesel,1600.0,Sedan,Grey,Giza,Individual,No,1.0,Good,12.0,1012000,No
2,CAR-52822,Skoda,Octavia,2009,224500.0,Automatic,Petrol,1400.0,Sedan,Silver,Banha,Dealer,Yes,2.0,Fair,11.0,229000,No
3,CAR-51133,Fiat,Tipo,2019,103800.0,Automatic,Petrol,1600.0,Sedan,Silver,ALEXANDRIA,Individual,No,2.0,Fair,7.0,319000,No
4,CAR-51465,Mitsubishi,Lancer,2022,50200.0,Manual,Hybrid,1600.0,Sedan,White,Cairo,Individual,No,NaN,Fair,8.0,425000,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,CAR-51818,Chery,Tiggo 7,2023,40800.0,Manual,Petrol,1600.0,SUV,Grey,Assiut,Individual,No,3.0,Good,7.0,1065000,No
2996,CAR-51600,bmw,320i,2022,60400.0,Automatic,Petrol,2000.0,Sedan,Red,Cairo,Individual,No,2.0,NaN,10.0,1409000,Yes
2997,CAR-50347,Hyundai,Tucson,2020,87100.0,Auto,Diesel,1600.0,SUV,Blue,Giza,Individual,No,1.0,Good,8.0,966000,Yes
2998,CAR-50986,Toyota,Corolla,2020,73900.0,Manual,Diesel,1800.0,Sedan,Silver,Alexandria,Individual,No,4.0,Excellent,12.0,774000,No
2999,CAR-50666,Kia,Cerato,2024,14100.0,Automatic,Petrol,1600.0,Sedan,White,Banha,Dealer,No,1.0,Good,14.0,1133000,Yes

In [19]:
df.isnull().sum()

listing_id               0
brand                    0
model                    0
year                     0
mileage_km             169
transmission            57
fuel_type               57
engine_cc              115
body_type                0
color                  142
city                    58
seller_type             57
accident_history         0
previous_owners        113
condition_rating       145
photos_count            85
price_egp                0
sold_within_30_days      0
dtype: int64

In [20]:
cols = [
    "transmission",
    "fuel_type",
    "color",
    "city",
    "seller_type"
]

df[cols] = df[cols].fillna("Unknown")
df

,listing_id,brand,model,year,mileage_km,transmission,fuel_type,engine_cc,body_type,color,city,seller_type,accident_history,previous_owners,condition_rating,photos_count,price_egp,sold_within_30_days
0,CAR-52762,MG,ZS,2021,64900.0,Automatic,Diesel,1500.0,SUV,Black,Giza,Individual,No,1.0,Fair,8.0,655000,Yes
1,CAR-52678,Kia,Cerato,2023,NaN,Automatic,Diesel,1600.0,Sedan,Grey,Giza,Individual,No,1.0,Good,12.0,1012000,No
2,CAR-52822,Skoda,Octavia,2009,224500.0,Automatic,Petrol,1400.0,Sedan,Silver,Banha,Dealer,Yes,2.0,Fair,11.0,229000,No
3,CAR-51133,Fiat,Tipo,2019,103800.0,Automatic,Petrol,1600.0,Sedan,Silver,ALEXANDRIA,Individual,No,2.0,Fair,7.0,319000,No
4,CAR-51465,Mitsubishi,Lancer,2022,50200.0,Manual,Hybrid,1600.0,Sedan,White,Cairo,Individual,No,NaN,Fair,8.0,425000,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,CAR-51818,Chery,Tiggo 7,2023,40800.0,Manual,Petrol,1600.0,SUV,Grey,Assiut,Individual,No,3.0,Good,7.0,1065000,No
2996,CAR-51600,bmw,320i,2022,60400.0,Automatic,Petrol,2000.0,Sedan,Red,Cairo,Individual,No,2.0,NaN,10.0,1409000,Yes
2997,CAR-50347,Hyundai,Tucson,2020,87100.0,Auto,Diesel,1600.0,SUV,Blue,Giza,Individual,No,1.0,Good,8.0,966000,Yes
2998,CAR-50986,Toyota,Corolla,2020,73900.0,Manual,Diesel,1800.0,Sedan,Silver,Alexandria,Individual,No,4.0,Excellent,12.0,774000,No
2999,CAR-50666,Kia,Cerato,2024,14100.0,Automatic,Petrol,1600.0,Sedan,White,Banha,Dealer,No,1.0,Good,14.0,1133000,Yes

In [21]:
df.isnull().sum()

listing_id               0
brand                    0
model                    0
year                     0
mileage_km             169
transmission             0
fuel_type                0
engine_cc              115
body_type                0
color                    0
city                     0
seller_type              0
accident_history         0
previous_owners        113
condition_rating       145
photos_count            85
price_egp                0
sold_within_30_days      0
dtype: int64

In [22]:
 
df["condition_rating"].value_counts()

condition_rating
Good         1400
Fair          639
Excellent     568
Poor          180
Name: count, dtype: int64

In [23]:
 
df['condition_rating_num'] = (
    df['condition_rating']
    .str.strip().str.title()
    .replace({'Poor': 1, 'Fair': 2, 'Good': 3, 'Excellent': 4})
    .astype(float)    
)

In [24]:
df

,listing_id,brand,model,year,mileage_km,transmission,fuel_type,engine_cc,body_type,color,city,seller_type,accident_history,previous_owners,condition_rating,photos_count,price_egp,sold_within_30_days,condition_rating_num
0,CAR-52762,MG,ZS,2021,64900.0,Automatic,Diesel,1500.0,SUV,Black,Giza,Individual,No,1.0,Fair,8.0,655000,Yes,2.0
1,CAR-52678,Kia,Cerato,2023,NaN,Automatic,Diesel,1600.0,Sedan,Grey,Giza,Individual,No,1.0,Good,12.0,1012000,No,3.0
2,CAR-52822,Skoda,Octavia,2009,224500.0,Automatic,Petrol,1400.0,Sedan,Silver,Banha,Dealer,Yes,2.0,Fair,11.0,229000,No,2.0
3,CAR-51133,Fiat,Tipo,2019,103800.0,Automatic,Petrol,1600.0,Sedan,Silver,ALEXANDRIA,Individual,No,2.0,Fair,7.0,319000,No,2.0
4,CAR-51465,Mitsubishi,Lancer,2022,50200.0,Manual,Hybrid,1600.0,Sedan,White,Cairo,Individual,No,NaN,Fair,8.0,425000,No,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,CAR-51818,Chery,Tiggo 7,2023,40800.0,Manual,Petrol,1600.0,SUV,Grey,Assiut,Individual,No,3.0,Good,7.0,1065000,No,3.0
2996,CAR-51600,bmw,320i,2022,60400.0,Automatic,Petrol,2000.0,Sedan,Red,Cairo,Individual,No,2.0,NaN,10.0,1409000,Yes,NaN
2997,CAR-50347,Hyundai,Tucson,2020,87100.0,Auto,Diesel,1600.0,SUV,Blue,Giza,Individual,No,1.0,Good,8.0,966000,Yes,3.0
2998,CAR-50986,Toyota,Corolla,2020,73900.0,Manual,Diesel,1800.0,Sedan,Silver,Alexandria,Individual,No,4.0,Excellent,12.0,774000,No,4.0
2999,CAR-50666,Kia,Cerato,2024,14100.0,Automatic,Petrol,1600.0,Sedan,White,Banha,Dealer,No,1.0,Good,14.0,1133000,Yes,3.0

In [25]:
df.isnull().sum()

listing_id                0
brand                     0
model                     0
year                      0
mileage_km              169
transmission              0
fuel_type                 0
engine_cc               115
body_type                 0
color                     0
city                      0
seller_type               0
accident_history          0
previous_owners         113
condition_rating        145
photos_count             85
price_egp                 0
sold_within_30_days       0
condition_rating_num    145
dtype: int64

In [26]:
df["brand"].value_counts()

brand
Hyundai          472
Toyota           372
Nissan           284
Kia              249
Chevrolet        199
MG               188
Renault          179
Skoda            162
Fiat             154
Chery            130
BMW              127
Mercedes-Benz    109
Mitsubishi        97
hyundai           18
toyota            17
chevrolet         12
nissan            11
Hyundai           10
TOYOTA             8
HYUNDAI            8
skoda              8
chery              7
mg                 7
Mercedes           6
KIA                6
kia                6
mitsubishi         6
NISSAN             6
Nissan             6
bmw                6
CHERY              5
fiat               5
mercedes-benz      5
Toyota             4
Chery              4
SKODA              4
renault            4
Chevrolet          4
CHEVROLET          3
RENAULT            3
MERCEDES-BENZ      3
hyundai            2
BMW                2
MITSUBISHI         2
Renault            2
Skoda              2
Fiat               2
Kia                1
MG                 1
NISSAN             1
FIAT               1
Mitsubishi         1
bmw                1
Name: count, dtype: int64

In [ ]:
df['brand'] = df['brand'].str.strip().str.title()
 
df['brand'] = df['brand'].replace({
    'Bmw': 'BMW',
    'Mg': 'MG',
    'Mercedes': 'Mercedes-Benz',
    'Mercedes Benz': 'Mercedes-Benz',
})

In [28]:

df['brand'].value_counts()

brand
Hyundai          510
Toyota           401
Nissan           308
Kia              262
Chevrolet        218
MG               196
Renault          188
Skoda            176
Fiat             162
Chery            146
BMW              136
Mercedes-Benz    123
Mitsubishi       106
Name: count, dtype: int64

In [31]:
df.isnull().sum()

listing_id                0
brand                     0
model                     0
year                      0
mileage_km              169
transmission              0
fuel_type                 0
engine_cc               115
body_type                 0
color                     0
city                      0
seller_type               0
accident_history          0
previous_owners         113
condition_rating        145
photos_count             85
price_egp                 0
sold_within_30_days       0
condition_rating_num    145
dtype: int64

In [33]:
for c in ['model', 'city', 'color', 'fuel_type', 'body_type', 'seller_type', 'transmission']:
    df[c] = df[c].str.strip().str.title()

In [37]:
df['transmission'] = df['transmission'].replace({'Auto': 'Automatic'})
df['body_type'] =df['body_type'].replace({'Suv' : 'SUV'})

In [42]:
df ['model'].value_counts()

model
Corolla    401
Elantra    386
Sunny      308
Cerato     262
Optra      218
Zs         196
Logan      188
Octavia    176
Tipo       162
Tiggo 7    146
320I       136
Tucson     124
C200       123
Lancer     106
Name: count, dtype: int64

In [43]:
df['model'] = df['model'].replace({'320I': '320i'})

In [44]:
df.isnull().sum()

listing_id                0
brand                     0
model                     0
year                      0
mileage_km              169
transmission              0
fuel_type                 0
engine_cc               115
body_type                 0
color                     0
city                      0
seller_type               0
accident_history          0
previous_owners         113
condition_rating        145
photos_count             85
price_egp                 0
sold_within_30_days       0
condition_rating_num    145
dtype: int64

In [ ]:
df

,listing_id,brand,model,year,mileage_km,transmission,fuel_type,engine_cc,body_type,color,city,seller_type,accident_history,previous_owners,condition_rating,photos_count,price_egp,sold_within_30_days,condition_rating_num
0,CAR-52762,MG,Zs,2021,64900.0,Automatic,Diesel,1500.0,SUV,Black,Giza,Individual,No,1.0,Fair,8.0,655000,Yes,2.0
1,CAR-52678,Kia,Cerato,2023,NaN,Automatic,Diesel,1600.0,Sedan,Grey,Giza,Individual,No,1.0,Good,12.0,1012000,No,3.0
2,CAR-52822,Skoda,Octavia,2009,224500.0,Automatic,Petrol,1400.0,Sedan,Silver,Banha,Dealer,Yes,2.0,Fair,11.0,229000,No,2.0
3,CAR-51133,Fiat,Tipo,2019,103800.0,Automatic,Petrol,1600.0,Sedan,Silver,Alexandria,Individual,No,2.0,Fair,7.0,319000,No,2.0
4,CAR-51465,Mitsubishi,Lancer,2022,50200.0,Manual,Hybrid,1600.0,Sedan,White,Cairo,Individual,No,NaN,Fair,8.0,425000,No,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,CAR-51818,Chery,Tiggo 7,2023,40800.0,Manual,Petrol,1600.0,SUV,Grey,Assiut,Individual,No,3.0,Good,7.0,1065000,No,3.0
2996,CAR-51600,BMW,320i,2022,60400.0,Automatic,Petrol,2000.0,Sedan,Red,Cairo,Individual,No,2.0,NaN,10.0,1409000,Yes,NaN
2997,CAR-50347,Hyundai,Tucson,2020,87100.0,Automatic,Diesel,1600.0,SUV,Blue,Giza,Individual,No,1.0,Good,8.0,966000,Yes,3.0
2998,CAR-50986,Toyota,Corolla,2020,73900.0,Manual,Diesel,1800.0,Sedan,Silver,Alexandria,Individual,No,4.0,Excellent,12.0,774000,No,4.0
2999,CAR-50666,Kia,Cerato,2024,14100.0,Automatic,Petrol,1600.0,Sedan,White,Banha,Dealer,No,1.0,Good,14.0,1133000,Yes,3.0

In [46]:

df['mileage_km'] = df['mileage_km'].fillna(df.groupby('year')['mileage_km'].transform('median'))
df['engine_cc'] = df['engine_cc'].fillna(df.groupby('model')['engine_cc'].transform('median'))
df['previous_owners'] = df['previous_owners'].fillna(df.groupby('year')['previous_owners'].transform('median')).round()

In [47]:
df

,listing_id,brand,model,year,mileage_km,transmission,fuel_type,engine_cc,body_type,color,city,seller_type,accident_history,previous_owners,condition_rating,photos_count,price_egp,sold_within_30_days,condition_rating_num
0,CAR-52762,MG,Zs,2021,64900.0,Automatic,Diesel,1500.0,SUV,Black,Giza,Individual,No,1.0,Fair,8.0,655000,Yes,2.0
1,CAR-52678,Kia,Cerato,2023,42100.0,Automatic,Diesel,1600.0,Sedan,Grey,Giza,Individual,No,1.0,Good,12.0,1012000,No,3.0
2,CAR-52822,Skoda,Octavia,2009,224500.0,Automatic,Petrol,1400.0,Sedan,Silver,Banha,Dealer,Yes,2.0,Fair,11.0,229000,No,2.0
3,CAR-51133,Fiat,Tipo,2019,103800.0,Automatic,Petrol,1600.0,Sedan,Silver,Alexandria,Individual,No,2.0,Fair,7.0,319000,No,2.0
4,CAR-51465,Mitsubishi,Lancer,2022,50200.0,Manual,Hybrid,1600.0,Sedan,White,Cairo,Individual,No,2.0,Fair,8.0,425000,No,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,CAR-51818,Chery,Tiggo 7,2023,40800.0,Manual,Petrol,1600.0,SUV,Grey,Assiut,Individual,No,3.0,Good,7.0,1065000,No,3.0
2996,CAR-51600,BMW,320i,2022,60400.0,Automatic,Petrol,2000.0,Sedan,Red,Cairo,Individual,No,2.0,NaN,10.0,1409000,Yes,NaN
2997,CAR-50347,Hyundai,Tucson,2020,87100.0,Automatic,Diesel,1600.0,SUV,Blue,Giza,Individual,No,1.0,Good,8.0,966000,Yes,3.0
2998,CAR-50986,Toyota,Corolla,2020,73900.0,Manual,Diesel,1800.0,Sedan,Silver,Alexandria,Individual,No,4.0,Excellent,12.0,774000,No,4.0
2999,CAR-50666,Kia,Cerato,2024,14100.0,Automatic,Petrol,1600.0,Sedan,White,Banha,Dealer,No,1.0,Good,14.0,1133000,Yes,3.0

In [48]:
df.isnull().sum()

listing_id                0
brand                     0
model                     0
year                      0
mileage_km                0
transmission              0
fuel_type                 0
engine_cc                 0
body_type                 0
color                     0
city                      0
seller_type               0
accident_history          0
previous_owners           0
condition_rating        145
photos_count             85
price_egp                 0
sold_within_30_days       0
condition_rating_num    145
dtype: int64

In [ ]:
df['photos_count'] = df['photos_count'].fillna(0)

In [ ]:
 
df['condition_rating_num'] = df['condition_rating_num'].fillna(
df.groupby('accident_history')['condition_rating_num'].transform('median')).round()

In [54]:

df['condition_rating'] = df['condition_rating_num'].replace({1: 'Poor', 2: 'Fair', 3: 'Good', 4: 'Excellent'})
df=df.drop(columns=['condition_rating_num'])

In [55]:
df.isnull().sum()

listing_id             0
brand                  0
model                  0
year                   0
mileage_km             0
transmission           0
fuel_type              0
engine_cc              0
body_type              0
color                  0
city                   0
seller_type            0
accident_history       0
previous_owners        0
condition_rating       0
photos_count           0
price_egp              0
sold_within_30_days    0
dtype: int64

In [56]:
df

,listing_id,brand,model,year,mileage_km,transmission,fuel_type,engine_cc,body_type,color,city,seller_type,accident_history,previous_owners,condition_rating,photos_count,price_egp,sold_within_30_days
0,CAR-52762,MG,Zs,2021,64900.0,Automatic,Diesel,1500.0,SUV,Black,Giza,Individual,No,1.0,Fair,8.0,655000,Yes
1,CAR-52678,Kia,Cerato,2023,42100.0,Automatic,Diesel,1600.0,Sedan,Grey,Giza,Individual,No,1.0,Good,12.0,1012000,No
2,CAR-52822,Skoda,Octavia,2009,224500.0,Automatic,Petrol,1400.0,Sedan,Silver,Banha,Dealer,Yes,2.0,Fair,11.0,229000,No
3,CAR-51133,Fiat,Tipo,2019,103800.0,Automatic,Petrol,1600.0,Sedan,Silver,Alexandria,Individual,No,2.0,Fair,7.0,319000,No
4,CAR-51465,Mitsubishi,Lancer,2022,50200.0,Manual,Hybrid,1600.0,Sedan,White,Cairo,Individual,No,2.0,Fair,8.0,425000,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,CAR-51818,Chery,Tiggo 7,2023,40800.0,Manual,Petrol,1600.0,SUV,Grey,Assiut,Individual,No,3.0,Good,7.0,1065000,No
2996,CAR-51600,BMW,320i,2022,60400.0,Automatic,Petrol,2000.0,Sedan,Red,Cairo,Individual,No,2.0,Good,10.0,1409000,Yes
2997,CAR-50347,Hyundai,Tucson,2020,87100.0,Automatic,Diesel,1600.0,SUV,Blue,Giza,Individual,No,1.0,Good,8.0,966000,Yes
2998,CAR-50986,Toyota,Corolla,2020,73900.0,Manual,Diesel,1800.0,Sedan,Silver,Alexandria,Individual,No,4.0,Excellent,12.0,774000,No
2999,CAR-50666,Kia,Cerato,2024,14100.0,Automatic,Petrol,1600.0,Sedan,White,Banha,Dealer,No,1.0,Good,14.0,1133000,Yes

In [57]:
df.describe()

,year,mileage_km,engine_cc,previous_owners,photos_count,price_egp
count,2932.000000,2.932000e+03,2932.000000,2932.000000,2932.000000,2.932000e+03
mean,2018.143247,1.090602e+05,1654.810709,1.878922,10.246589,7.553889e+05
std,37.698511,2.658950e+05,522.325088,0.993328,8.527970,2.065315e+06
min,0.000000,0.000000e+00,0.000000,1.000000,0.000000,0.000000e+00
25%,2017.000000,5.057500e+04,1500.000000,1.000000,8.000000,3.287500e+05
50%,2020.000000,8.555000e+04,1600.000000,2.000000,10.000000,5.520000e+05
75%,2022.000000,1.335000e+05,1600.000000,2.000000,12.250000,9.370000e+05
max,2050.000000,9.999999e+06,20000.000000,6.000000,300.000000,1.000000e+08

In [58]:
df.to_csv('cleaned_used_cars_dataset.csv', index=False)

# Done.....